#!/usr/bin/env python
import os
import sys
import subprocess

folder = sys.argv[1]
DEBUG = "DEBUG" in os.environ

fswatch = subprocess.Popen(
    [
        "/usr/local/bin/fswatch", "-x",
        "--event", "Created",
        "--event", "Removed",
        "--batch-marker=I-AM-THE-BATCH-MARKER",
        folder
    ],
    stdout=subprocess.PIPE,
    shell=False,
)

def parse(line):
    if line == "I-AM-THE-BATCH-MARKER":
        return "", ("marker", )
    elif line.endswith(" Created Removed"):
        return line[:-len(" Created Removed")], ("created", "removed")
    elif line.endswith(" Created"):
        return line[:-len(" Created")], ("created", )
    elif line.endswith(" Removed"):
        return line[:-len(" Removed")], ("removed", )
    else:
        raise ValueError(line)


changes = set()
for line in fswatch.stdout:
    filename, actions = parse(line.decode("us-ascii").strip())
    if DEBUG: print((filename, actions))

    if actions == ("created", "removed"):
        continue

    elif actions == ("created", ):
        changes.add(filename)

    elif actions == ("removed", ):
        if filename in changes:
            changes.remove(filename)
        elif filename.endswith("~") and filename[:-1] in changes:
            # some vim temp file stuff?
            changes.remove(filename[:-1])
        else:
            changes.add(filename)

    elif actions == ("marker", ):
        if not changes:
            continue

        index_file = folder + "/.fileindex"
        if changes != set([index_file]):
            if DEBUG: print("changes are %r" % changes)
            if DEBUG: print("reindexing...")
            subprocess.Popen(
                ["/usr/bin/find", folder, "-type", "f"],
                stdout=open(index_file, "w"),
                shell=False,
            ).wait()
            if DEBUG: print("done.")
        changes = set()

    else:
        # should never get here
        raise ValueError(actions)
