#!/bin/bash

HERE=$PWD
ROOT=$HERE

while true; do
    if [ "$ROOT" = "/" ]; then
        # found nothing, search current dir
        ROOT=$HERE
        break
    fi
    if [ -d "$ROOT/.git" ]; then
        break
    fi
    if [ "$ROOT" = "$HOME" ]; then
        break
    fi
    ROOT=$(dirname "$ROOT")
done

if [ "$FZF_EXCLUDE" != "" ] ;then
    exec find $ROOT -type f | egrep -i -v "$FZF_EXCLUDE" | $HOME/dotfiles/relpath $HERE
else
    exec find $ROOT -type f | $HOME/dotfiles/relpath $HERE
fi
