#!/bin/bash

HERE=${PWD}

while true; do
    if [ "${HERE}" = "/" ]; then
        # found nothing, search current dir
        HERE=${PWD}
        break
    fi
    if [ -d "${HERE}/.git" ]; then
        break
    fi
    if [ "${HERE}" = "${HOME}" ]; then
        break
    fi
    HERE=$(dirname "${HERE}")
done

if [ $(uname) = "Darwin" ]; then
    exec find ${HERE} ${FZF_FIND_OPTS} -type f | sed "s,^${HERE}/,,"
else
    exec find ${HERE} ${FZF_FIND_OPTS} -type f -printf "%P\n"
fi
