#!/bin/bash

HERE=$PWD
ROOT=$HERE

while true; do
    if [ "$ROOT" = "/" ]; then
        # found nothing, search current dir
        ROOT=$HERE
        break
    fi
    if [ -d "$ROOT/.git" ]; then
        break
    fi
    if [ "$ROOT" = "$HOME" ]; then
        break
    fi
    ROOT=$(dirname "$ROOT")
done

exec find $ROOT $FZF_FIND_OPTS -not -name *.swp -not -name *.swo -type f | python $HOME/dotfiles/relpath.py $HERE
