#!/bin/bash
# This hook is run after a new virtualenv is activated.

parent="$PWD"
envname="$(basename $VIRTUAL_ENV)"
envdir="$parent/$envname"

postactivate=$VIRTUAL_ENV/bin/postactivate

echo "cd $envdir"             >> $postactivate
echo                          >> $postactivate

if [ ! -e $envdir ]; then
    mkdir -p $envdir
fi

cd $envdir

